<?php
require __DIR__.'/app/view.php';
site_header('Start','index.html');
$bookItems=entries('book',3); $articleItems=entries('article',3);
?><main id="content"><section class="igs-hero"><div class="igs-wrap igs-hero-grid"><div class="igs-hero-copy"><span class="igs-eyebrow igs-hero-label">Forschung · Bildung · Erinnerung</span><h1><?=h(setting('tagline'))?></h1><p><?=h(setting('home_intro'))?></p><div class="igs-hero-actions"><a class="igs-button" href="/ueber-uns.html">Das Institut kennenlernen <span aria-hidden="true">↗</span></a><a class="igs-link-light" href="/ausstellungen.html">Ausstellungen ansehen <span aria-hidden="true">→</span></a></div></div><div class="igs-hero-art"><?php photo_layers(setting('home_hero'),'Fotografie eines Innenraums','igs-hero-photo');?><span class="igs-art-note">Geschichte in Perspektiven</span></div></div><span class="igs-hero-number" aria-hidden="true">01 / IGSL</span></section>
<section class="igs-intro igs-wrap"><span class="igs-eyebrow">Was uns antreibt</span><div><h2><?=h(setting('intro_heading'))?></h2><p><?=h(setting('intro_body'))?></p></div></section>
<section class="igs-feature-section"><div class="igs-wrap"><div class="igs-section-head"><div><span class="igs-eyebrow">Unsere Arbeit</span><h2><?=h(setting('features_heading'))?></h2></div><p><?=h(setting('features_intro'))?></p></div><div class="igs-feature-grid"><a href="/ausstellungen.html" class="igs-feature igs-feature-large" style="--feature-image:url('/<?=h(safe_path(setting('feature_exhibitions_image')))?>')"><span>01 / Ausstellungen</span><h3><?=h(setting('feature_exhibitions'))?></h3><b aria-hidden="true">↗</b></a><a href="/workshops.html" class="igs-feature" style="--feature-image:url('/<?=h(safe_path(setting('feature_workshops_image')))?>')"><span>02 / Workshops</span><h3><?=h(setting('feature_workshops'))?></h3><b aria-hidden="true">↗</b></a><a href="/forschung.html" class="igs-feature" style="--feature-image:url('/<?=h(safe_path(setting('feature_research_image')))?>')"><span>03 / Forschung</span><h3><?=h(setting('feature_research'))?></h3><b aria-hidden="true">↗</b></a></div></div></section>
<section class="igs-list-section igs-wrap"><div class="igs-section-head"><div><span class="igs-eyebrow">Publikationen</span><h2><?=h(setting('books_heading'))?></h2></div><a class="igs-text-link" href="/buecher.html">Alle Bücher <span aria-hidden="true">↗</span></a></div><div class="igs-entry-grid"><?php foreach($bookItems as $item) entry_card($item); ?></div></section>
<section class="igs-list-section igs-wrap"><div class="igs-section-head"><div><span class="igs-eyebrow">Aktuelles</span><h2><?=h(setting('articles_heading'))?></h2></div><a class="igs-text-link" href="/aktuelles.html">Alle Beiträge <span aria-hidden="true">↗</span></a></div><div class="igs-entry-grid"><?php foreach($articleItems as $item) entry_card($item); ?></div></section>
<section class="igs-cta"><div class="igs-wrap"><span class="igs-eyebrow">Im Gespräch bleiben</span><h2><?=h(setting('cta_heading'))?></h2><a class="igs-button igs-button-light" href="/kontakt.html">Kontakt aufnehmen <span aria-hidden="true">↗</span></a></div></section></main><?php site_footer(); ?>
