<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';

function site_header(string $title, string $active=''): void {
    security_headers();
    $nav=['index.html'=>'Start','aktuelles.html'=>'Aktuelles','ausstellungen.html'=>'Ausstellungen','workshops.html'=>'Bildungsangebote','buecher.html'=>'Publikationen','ueber-uns.html'=>'Über uns'];
    $more=['vortraege.html'=>'Vorträge','forschung.html'=>'Forschung','exkursionen.html'=>'Exkursionen','presse.html'=>'Presse'];
    ?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=h(setting('home_intro'))?>"><title><?=h($title)?> | <?=h(setting('site_name'))?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="/assets/css/editorial.css?v=20261007c"></head><body class="igs-body"><a class="skip-link" href="#content">Zum Inhalt springen</a><header class="igs-header"><div class="igs-header-inner"><a class="igs-brand" href="/index.html" aria-label="IGSL – Startseite"><img src="/assets/img/logo/igs-logo.png" alt=""><span>Institut für<br>Geschichte und Soziales<small>ASBL · Luxembourg</small></span></a><button class="igs-menu-button" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Navigation öffnen"><span></span><span></span><span></span></button><nav class="igs-nav" id="site-nav" aria-label="Hauptnavigation"><?php foreach($nav as $url=>$label): ?><a href="/<?=h($url)?>" <?=($active===$url?'aria-current="page"':'')?>><?=h($label)?></a><?php endforeach; ?><details class="igs-nav-more"><summary>Mehr <span aria-hidden="true">⌄</span></summary><div><?php foreach($more as $url=>$label): ?><a href="/<?=h($url)?>" <?=($active===$url?'aria-current="page"':'')?>><?=h($label)?></a><?php endforeach; ?></div></details><a class="igs-nav-contact" href="/kontakt.html">Kontakt <span aria-hidden="true">↗</span></a></nav></div></header><?php
}
function site_footer(): void {
    ?><footer class="igs-footer"><div class="igs-wrap igs-footer-grid"><div><div class="igs-footer-brand">IGSL<span>Institut für Geschichte und Soziales ASBL</span></div><p>Forschung, Bildung und Erinnerung in Luxemburg.</p></div><div><h2>Entdecken</h2><a href="/ausstellungen.html">Ausstellungen</a><a href="/buecher.html">Publikationen</a><a href="/workshops.html">Bildungsangebote</a></div><div><h2>Kontakt</h2><p><?=h(setting('contact_address'))?></p><a href="mailto:<?=h(setting('contact_email'))?>"><?=h(setting('contact_email'))?></a><a href="/kontakt.html">Kontaktseite</a></div><div><h2>Information</h2><a href="/impressum.html">Impressum</a><a href="/datenschutz.html">Datenschutz</a><p>© <?=date('Y')?> IGSL</p></div></div></footer><script src="/assets/js/site.js" defer></script></body></html><?php
}
function photo_layers(string $image, string $alt, string $class=''): void {
    $image=safe_path($image) ?: 'assets/img/hero/hero-01.jpg';
    ?><div class="igs-photo-layers <?=h($class)?>" tabindex="0" aria-label="<?=h($alt)?>"><div class="igs-photo-plane igs-photo-back" style="--photo:url('/<?=h($image)?>')"></div><div class="igs-photo-plane igs-photo-middle" style="--photo:url('/<?=h($image)?>')"></div><div class="igs-photo-plane igs-photo-front" style="--photo:url('/<?=h($image)?>')"></div><span class="igs-photo-corner" aria-hidden="true"></span></div><?php
}
function entry_card(array $entry): void {
    $image=safe_path($entry['image']); $link=safe_link($entry['link']);
    $href=$link===''?'/entry.php?id='.(int)$entry['id']:(str_starts_with($link,'https://')||str_starts_with($link,'mailto:')||str_starts_with($link,'#')?$link:'/'.$link);
    ?><article class="igs-entry-card"><a href="<?=h($href)?>" class="igs-entry-image" aria-label="<?=h($entry['title'])?>"><?php if($image):?><img src="/<?=h($image)?>" alt="<?=h($entry['title'])?>" loading="lazy"><?php else: ?><span class="igs-entry-placeholder" aria-hidden="true"><small>IGSL · LUXEMBURG</small><strong><?=h($entry['kind'])?></strong><i>Forschung<br>und Erinnerung</i></span><?php endif;?></a><div class="igs-entry-content"><span class="igs-eyebrow"><?=h($entry['kind'])?></span><h3><a href="<?=h($href)?>"><?=h($entry['title'])?></a></h3><?php if($entry['summary']):?><p><?=h($entry['summary'])?></p><?php endif;?><a class="igs-text-link" href="<?=h($href)?>">Mehr erfahren <span aria-hidden="true">↗</span></a></div></article><?php
}
