<?php
require __DIR__.'/common.php'; require_login();
$pages=db()->query('SELECT slug,title FROM pages ORDER BY title')->fetchAll();
$books=db()->query("SELECT * FROM entries WHERE type='book' ORDER BY position,id")->fetchAll();
$articles=db()->query("SELECT * FROM entries WHERE type='article' ORDER BY position,id")->fetchAll();
$mediaCount=(int)db()->query('SELECT COUNT(*) FROM media')->fetchColumn();
admin_header('Übersicht'); ?><div class="admin-heading"><div><span class="admin-kicker">Inhaltsverwaltung</span><h1>Ihre Website. Ihre Inhalte.</h1><p>Änderungen werden nach dem Speichern sofort auf der Website sichtbar.</p></div><a class="admin-outline" href="/index.html" target="_blank" rel="noopener">Website ansehen ↗</a></div><div class="admin-stats"><a href="#pages"><strong><?=count($pages)?></strong><span>Seiten</span></a><a href="#books"><strong><?=count($books)?></strong><span>Bücher</span></a><a href="#articles"><strong><?=count($articles)?></strong><span>Beiträge</span></a><a href="/admin/media.php"><strong><?=$mediaCount?></strong><span>Uploads</span></a></div>
<section class="admin-panel" id="settings"><div class="admin-panel-head"><div><span class="admin-kicker">Grundlagen</span><h2>Startseite & Kontakt</h2></div><a class="admin-outline" href="/admin/edit.php?type=settings">Bearbeiten →</a></div><p>Seitentitel, Einleitung, Titelbild und Kontaktdaten.</p></section>
<section class="admin-panel" id="pages"><div class="admin-panel-head"><div><span class="admin-kicker">Inhalte</span><h2>Seiten</h2></div></div><div class="admin-list"><?php foreach($pages as $p):?><a href="/admin/edit.php?type=page&amp;slug=<?=h($p['slug'])?>"><span><?=h($p['title'])?></span><small>/<?=h($p['slug'])?>.html</small><b>Bearbeiten ↗</b></a><?php endforeach;?></div></section>
<section class="admin-panel" id="books"><div class="admin-panel-head"><div><span class="admin-kicker">Bibliothek</span><h2>Bücher</h2></div><a class="admin-outline" href="/admin/edit.php?type=book">+ Buch hinzufügen</a></div><div class="admin-list"><?php foreach($books as $item):?><a href="/admin/edit.php?type=book&amp;id=<?=$item['id']?>"><span><?=h($item['title'])?></span><small><?= $item['published']?'Sichtbar':'Archiviert' ?></small><b>Bearbeiten ↗</b></a><?php endforeach;?></div></section>
<section class="admin-panel" id="articles"><div class="admin-panel-head"><div><span class="admin-kicker">Journal</span><h2>Beiträge</h2></div><a class="admin-outline" href="/admin/edit.php?type=article">+ Beitrag hinzufügen</a></div><div class="admin-list"><?php foreach($articles as $item):?><a href="/admin/edit.php?type=article&amp;id=<?=$item['id']?>"><span><?=h($item['title'])?></span><small><?= $item['published']?'Sichtbar':'Archiviert' ?></small><b>Bearbeiten ↗</b></a><?php endforeach;?></div></section><?php admin_footer(); ?>
